#include <stdio.h>
#include <esp_log.h>
#include <esp_system.h>
#include <nvs_flash.h>
#include <sys/param.h>
#include <string.h>
#include <inttypes.h>
#include "sdkconfig.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include "freertos/semphr.h"
#include "freertos/timers.h"
#include "freertos/event_groups.h"
#include "freertos/stream_buffer.h"
#include "freertos/message_buffer.h"
#include "Timer.h"
#include "UART.h"
#include "lvgl.h"
#include "LVGL_UI.h"
#include "GPIO.h"
#include "led_strip.h"
#include "FOC.h"
#include "TCP_Server.h"
#include "TCP_Client.h"
#include "UDP_Client.h"
#include "UDP_Server.h"
#include "WIFI.h"
#include "TemperatureSensor.h"
#include "MathFun.h"
#include "IIC.h"
#include "AS5600.h"
#include "DataType.h"
#include "ADC.h"
#include "SDIO.h"
#include "Key.h"
#include "Camera.h"
#include "MorseCode.h"
#include "mpu6050.h"
#include "esp_smartconfig.h"


